"""add: Deploy, Snapshot

Revision ID: 006a9e094af1
Revises: 05390c87a0be
Create Date: 2026-05-04 11:44:03.731187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006a9e094af1'
down_revision: Union[str, Sequence[str], None] = '05390c87a0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deploys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'backup', 'format', 'install', 'restore', 'done', 'failed', name='deploystatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('backup_path', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deploy_id', sa.String(), nullable=False),
    sa.Column('disks', sa.JSON(), nullable=True),
    sa.Column('users', sa.JSON(), nullable=True),
    sa.Column('programs', sa.JSON(), nullable=True),
    sa.Column('smart', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deploy_id'], ['deploys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots')
    op.drop_table('deploys')
    # ### end Alembic commands ###
